// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDbDz_InGwMH_X8pPRu-S-8CqRxMTdzUo',
    appId: '1:678914657887:web:921d2ea52edf5e824355ea',
    messagingSenderId: '678914657887',
    projectId: 'my-new-shawl',
    authDomain: 'my-new-shawl.firebaseapp.com',
    storageBucket: 'my-new-shawl.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW-kR4uOQ5yve9uJ1AlrZ9wirlH9I-ReQ',
    appId: '1:678914657887:android:b67b7707a7ba407c4355ea',
    messagingSenderId: '678914657887',
    projectId: 'my-new-shawl',
    storageBucket: 'my-new-shawl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpeQNgUQwZmlwrbYqCJarEPo_g5ZXz2Rg',
    appId: '1:678914657887:ios:fe79f268d0c01f804355ea',
    messagingSenderId: '678914657887',
    projectId: 'my-new-shawl',
    storageBucket: 'my-new-shawl.appspot.com',
    iosClientId:
        '678914657887-t4rj6spokqqn1bgt91s37i6batgs0sc5.apps.googleusercontent.com',
    iosBundleId: 'com.example.shawl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpeQNgUQwZmlwrbYqCJarEPo_g5ZXz2Rg',
    appId: '1:678914657887:ios:fe79f268d0c01f804355ea',
    messagingSenderId: '678914657887',
    projectId: 'my-new-shawl',
    storageBucket: 'my-new-shawl.appspot.com',
    iosClientId:
        '678914657887-t4rj6spokqqn1bgt91s37i6batgs0sc5.apps.googleusercontent.com',
    iosBundleId: 'com.example.shawl',
  );
}
